const SOROS_CONFIG = {
  SUPABASE_URL: "https://hxnzqfezvksxwipayqra.supabase.co",
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bnpxZmV6dmtzeHdpcGF5cXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTEyNzYsImV4cCI6MjA4ODkyNzI3Nn0.-TLzoRFhROTEOrVEVJIBsGS2vajMEXxko_dsMgoni4E",
  AUTO_RETRY_SECONDS: 5,
  ASSET_LABEL: "BTC/USD",
  BINANCE_SYMBOL: "BTCUSDT",
  MIN_SCORE_TO_TRADE: 80,
  HISTORY_LIMIT: 50,
  MAX_DB_ROWS: 10000,
  DELETE_OLD_ROWS: 5000
};
