const SOROS_CONFIG = {
  SUPABASE_URL: "https://hxnzqfezvksxwipayqra.supabase.co",
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bnpxZmV6dmtzeHdpcGF5cXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTEyNzYsImV4cCI6MjA4ODkyNzI3Nn0.-TLzoRFhROTEOrVEVJIBsGS2vajMEXxko_dsMgoni4E",
  SIGNAL_DURATION: 5,
  AUTO_RETRY_SECONDS: 2,
  ASSET_LABEL: "BTC/USD",
  BINANCE_SYMBOL: "BTCUSDT",
  MIN_SCORE_TO_TRADE: 80
};
